name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  # call-workflow:
  #   uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: github.com/gihyunk/github_action/.github/workflows/reusable-githyb-action.yml
    with:
      username: mona
