name: Release Auto-PR
on:
  push:
    branches: ['releases/**']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${GITHUB_REF#refs/heads/} into main"
        pr_template: "pull_request_template.md"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}