name: Call a reusable workflow
on: [push]

jobs:    
  call-workflow-passing-data:
    strategy:
      matrix:
        service:
          - sub-project-a
          - sub-project-b
          - sub-project-c
    steps:
      - uses: ./.github/workflows/reusable-github-action.yml
        with:
          username: ${{ matrix.service }}
