name: Call a reusable workflow
#on: [push]
on:
  push:
    paths:
      - 'sub-project-a/**'

jobs:    
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-github-action.yml
        with:
          username: mona
    # strategy:
    #   matrix:
    #     service:
    #       - sub-project-a
    #       - sub-project-b
    #       - sub-project-c
    # runs-on: [linux]
    # steps:
    #   - uses: ./.github/workflows/reusable-github-action.yml
    #     with:
    #       username: ${{ matrix.service }}
