name: my-actions

env:
  SUB_PATH: sub-project-a

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: echo "hello $SUB_PATH"
