name: reusable-github-action
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/workflows/my-action
        with:
          username: ${{ inputs.username }}

  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v