name: Call a reusable workflow

on:
  push:
    paths:
      - 'sub-project-b/**'
    branches:
      - main
      - releases/**

jobs:    
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-github-action.yml
    with:
      project: sub-project-b
    # strategy:
    #   matrix:
    #     service:
    #       - sub-project-b
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: ./.github/workflows/reusable-github-action.yml
    #     with:
    #       project: ${{ matrix.service }}
