name: Call a reusable workflow

on:
  push:
    paths:
      - 'sub-project-b/**'
    branches:
      - main
      - releases/**

jobs:    
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-github-action.yml
    with:
      project: sub-project-b